#!/usr/bin/env python3
"""
Interactive setup script for LeadGen India
Helps create .env file with proper configuration
"""
import os
import json
from pathlib import Path


def main():
    print("=" * 60)
    print("  LeadGen India - Environment Setup")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    if Path('.env').exists():
        response = input(".env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    config = {}
    
    # API Keys
    print("\n📌 API Keys (required)")
    print("-" * 60)
    config['SERPAPI_KEY'] = input("SerpAPI Key: ").strip()
    config['OPENROUTER_KEY'] = input("OpenRouter Key: ").strip()
    config['HUNTER_KEY'] = input("Hunter.io Key (optional, press Enter to skip): ").strip()
    
    # Google Sheets
    print("\n📊 Google Sheets Configuration")
    print("-" * 60)
    config['SHEET_ID'] = input("Google Sheet ID: ").strip()
    
    # Service Account
    print("\n🔐 Service Account Setup")
    print("-" * 60)
    print("Choose how to provide service account credentials:")
    print("  1. Use service_account.json file (recommended)")
    print("  2. Paste JSON content directly")
    choice = input("Enter choice (1 or 2): ").strip()
    
    if choice == '1':
        json_file = input("Path to service_account.json [./service_account.json]: ").strip()
        if not json_file:
            json_file = 'service_account.json'
        
        if Path(json_file).exists():
            print(f"✓ Found {json_file}")
            config['GOOGLE_SERVICE_ACCOUNT_FILE'] = json_file
        else:
            print(f"⚠️  File not found: {json_file}")
            print("You can add it later.")
    
    elif choice == '2':
        print("Paste your service account JSON (press Enter twice when done):")
        lines = []
        while True:
            line = input()
            if not line:
                break
            lines.append(line)
        
        json_str = '\n'.join(lines)
        try:
            # Validate JSON
            json.loads(json_str)
            config['GOOGLE_SERVICE_ACCOUNT_JSON'] = json_str
            print("✓ Valid JSON")
        except json.JSONDecodeError:
            print("⚠️  Invalid JSON. You can add it later to .env file.")
    
    # Settings
    print("\n⚙️  Pipeline Settings")
    print("-" * 60)
    min_score = input("Minimum lead score (1-10) [7]: ").strip()
    config['MIN_SCORE'] = min_score if min_score else '7'
    
    max_concurrent = input("Max concurrent scrapes (1-10) [5]: ").strip()
    config['MAX_CONCURRENT'] = max_concurrent if max_concurrent else '5'
    
    # Write .env file
    print("\n💾 Writing .env file...")
    with open('.env', 'w', encoding='utf-8') as f:
        f.write("# LeadGen India Configuration\n")
        f.write("# Generated by setup_env.py\n\n")
        
        f.write("# ── API Keys ──────────────────────────────────────\n")
        f.write(f"SERPAPI_KEY={config.get('SERPAPI_KEY', '')}\n")
        f.write(f"OPENROUTER_KEY={config.get('OPENROUTER_KEY', '')}\n")
        f.write(f"HUNTER_KEY={config.get('HUNTER_KEY', '')}\n\n")
        
        f.write("# ── Google Sheets ─────────────────────────────────\n")
        f.write(f"SHEET_ID={config.get('SHEET_ID', '')}\n\n")
        
        if 'GOOGLE_SERVICE_ACCOUNT_FILE' in config:
            f.write(f"GOOGLE_SERVICE_ACCOUNT_FILE={config['GOOGLE_SERVICE_ACCOUNT_FILE']}\n\n")
        elif 'GOOGLE_SERVICE_ACCOUNT_JSON' in config:
            f.write(f"GOOGLE_SERVICE_ACCOUNT_JSON='{config['GOOGLE_SERVICE_ACCOUNT_JSON']}'\n\n")
        
        f.write("# ── Pipeline Settings ─────────────────────────────\n")
        f.write(f"MIN_SCORE={config.get('MIN_SCORE', '7')}\n")
        f.write(f"MAX_CONCURRENT={config.get('MAX_CONCURRENT', '5')}\n")
    
    print("✓ .env file created successfully!")
    
    # Test configuration
    print("\n🧪 Testing configuration...")
    try:
        from config import get_config, validate_config
        cfg = get_config()
        errors = validate_config(cfg)
        
        if errors:
            print("⚠️  Configuration issues found:")
            for err in errors:
                print(f"  - {err}")
        else:
            print("✓ Configuration is valid!")
    except Exception as e:
        print(f"⚠️  Could not validate config: {e}")
    
    print("\n" + "=" * 60)
    print("Setup complete! Next steps:")
    print("  1. Review .env file and add any missing values")
    print("  2. Test config: python config.py")
    print("  3. Run pipeline: python cron_job.py")
    print("  4. Start dashboard: streamlit run app.py")
    print("=" * 60)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
